<!-- llmcheats:begin -->
<!-- Regenerated by llmcheats. Do not edit inside these markers.
     Project memory goes BELOW the closing marker, where it is preserved. -->

## Routing

Prefix your request and the matching playbook is used. No prefix: classify from
the trigger list in `.llmcheats/cheats/routing.md`, say which in one sentence,
and proceed. Read the playbook before acting on it.

| Prefix      | Playbook                |     | Prefix      | Playbook                |
| ----------- | ----------------------- | --- | ----------- | ----------------------- |
| `feature:`  | `workflows/feature.md`  |     | `chore:`    | `workflows/chore.md`    |
| `bug:`      | `workflows/bug.md`      |     | `migrate:`  | `workflows/migrate.md`  |
| `hotfix:`   | `workflows/hotfix.md`   |     | `release:`  | `workflows/release.md`  |
| `refactor:` | `workflows/refactor.md` |     | `rollback:` | `workflows/rollback.md` |
| `review:`   | `workflows/review.md`   |     | `prompt:`   | `workflows/prompt.md`   |

Paths are under `.llmcheats/cheats/`. `index.md` says how to read the rest;
`.llmcheats/stack.md` says what this repo actually is.

## Escalate, and the floor

**Escalate out of a one-pass job** when the work touches auth, secrets, crypto,
payments or PII; a schema migration or backfill; a production deploy; a published
contract; or a diff over ~400 lines. Checked at intake *and* mid-task.

**The floor, whatever the flow** (`practices/floor.md`): secrets never committed
or logged; SQL parameterized and input validated; no authz check weakened; no
test deleted and no lint suppression added to green a build; errors handled,
never swallowed; nothing destructive on shared state without a go-ahead.

<!-- llmcheats:end -->

# Project

<!-- Everything below is yours. llmcheats preserves it across installs and
     re-runs. Keep the whole file under ~120 lines, no section past 20. -->

{{ONE OR TWO SENTENCES: what this system is and who uses it}}

## How to run it

<!-- Commands only, each one observed in this repo. Delete any line you could
     not source; do not guess a plausible command. These columns are sized for
     the placeholders — re-align them around the commands you substitute in. -->

| Task        | Command       |
| ----------- | ------------- |
| build       | `{{BUILD}}`   |
| test        | `{{TEST}}`    |
| lint        | `{{LINT}}`    |
| format      | `{{FORMAT}}`  |
| migrate     | `{{MIGRATE}}` |
| run locally | `{{RUN}}`     |

## Architecture decisions

<!-- The architecture this project ACTUALLY follows, and every place it departs
     from .llmcheats/docs/ with the reason. One line each; name the ADR or plan
     file that holds the argument. -->

- {{e.g. Handlers call services directly; no repository layer — see docs/adr/003.md}}

## DevOps decisions

<!-- Delete this section entirely if this repo does not deploy. -->

- deploy: `{{DEPLOY}}`
- rollback: `{{ROLLBACK}}`
- {{migration ordering, feature flags, where secrets come from}}

## Review rules

<!-- What a reviewer of THIS repo blocks on, beyond the floor. -->

- {{e.g. every new endpoint needs an authorization-matrix test}}

## Development patterns

<!-- Conventions a diff would otherwise break: error mapping, naming, where
     tests live, module boundaries. -->

- {{e.g. errors wrapped with %w; sentinel errors in errors.go per package}}

### Do not touch

<!-- Generated files, vendored code, paths that look editable and are not. -->

- {{e.g. api/gen/** — regenerate with `make generate`}}

## Keeping this file current

Add a line when something repeats: the same correction twice, the same mistake
twice, something review caught that the next session should have known. One
occurrence is noise; twice is a convention nobody wrote down.

Write the decision in the run that took it — deferred, it gets re-litigated next
session.

Out: secrets, hostnames, customer names, status ("currently working on X"),
anything `git log` already answers, and copies of `.llmcheats/docs/` — reference
those by filename.
